# Generated by Django 4.2 on 2023-10-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_homeseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
