# Generated by Django 4.2 on 2023-10-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_company_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_last',
            field=models.CharField(default='company', max_length=255),
        ),
    ]
