# Generated by Django 4.2 on 2023-10-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_company_company_last'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_address',
            new_name='companyaddress',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_last',
            new_name='companylast',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='companyname',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_phone',
            new_name='companyphone',
        ),
    ]
