# Generated by Django 4.2 on 2023-10-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeseller',
            name='seller_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
