# Generated by Django 4.2 on 2023-10-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_img',
        ),
        migrations.AddField(
            model_name='product',
            name='product_imp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
