# Generated by Django 4.2 on 2023-10-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_customer_cart_alter_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='customer_name',
            new_name='c_name',
        ),
    ]
