# Generated by Django 4.2 on 2023-10-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_customer_name_shippingaddress_c_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='c_name',
        ),
    ]
